// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MapAPI.Models.Test;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MapAPI.Data
{
    public partial class MapSQLContext
    {
        private IMapSQLContextProcedures _procedures;

        public virtual IMapSQLContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MapSQLContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMapSQLContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class MapSQLContextProcedures : IMapSQLContextProcedures
    {
        private readonly MapSQLContext _context;

        public MapSQLContextProcedures(MapSQLContext context)
        {
            _context = context;
        }
    }
}
