// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MapAPI.Models.Test;

public partial class GeoDataImage
{
    public int? Id { get; set; }

    public int? GeoData { get; set; }

    public string FileName { get; set; }

    public virtual GeoData GeoDataNavigation { get; set; }
}