// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using NetTopologySuite.Geometries;

namespace MapAPI.Models.Test;

public partial class GeoData
{
    public int Id { get; set; }

    /// <summary>
    /// 對應Tag表單
    /// </summary>
    public int? Tag { get; set; }

    /// <summary>
    /// geography
    /// </summary>
    public Geometry Geo { get; set; }

    /// <summary>
    /// 中文描述
    /// </summary>
    public string Chinese { get; set; }

    /// <summary>
    /// 英文描述
    /// </summary>
    public string English { get; set; }

    /// <summary>
    /// 日期
    /// </summary>
    public DateTime? Date { get; set; }

    public string Describe { get; set; }

    public virtual Tag TagNavigation { get; set; }
}