// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MapAPI.Models.Test;

public partial class Tag
{
    public int Id { get; set; }

    /// <summary>
    /// Tag Chinese describe
    /// </summary>
    public string Chinese { get; set; }

    /// <summary>
    /// Tag English describe
    /// </summary>
    public string English { get; set; }

    /// <summary>
    /// Tag level
    /// </summary>
    public int? Level { get; set; }

    public virtual ICollection<GeoData> GeoData { get; set; } = new List<GeoData>();
}