// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MapAPI.Models.Test;

public partial class Test
{
    public int Id { get; set; }

    public int? Tag { get; set; }

    public double? Lat { get; set; }

    public double? Lon { get; set; }
}